package kronos.fsm;

public enum PartStates {
		INIT,
		LIGHTBARRIER_1,
		BETWEEN_L1_L2,
		LIGHTBARRIER_2,
		BETWEEN_L2_L3,
		LIGHTBARRIER_3,
		MILLING_STATION,
		BETWEEN_L3_L4,
		LIGHTBARRIER_4,
		DRILLINGSTATION,
		BETWEEN_L4_L5,
		LIGHTBARRIER_5,
		SPECTRAL_ANALYSIS,
		FINISH
}
