package kronos.fsm;

public enum Triggers {
	LIGHTBARRIER_1_INTERRUPT, //something is between the light barrier
	LIGHTBARRIER_1_CONNECT,   //the object moved on and the light barrier is connected
	LIGHTBARRIER_2_INTERRUPT,
	LIGHTBARRIER_2_CONNECT,
	LIGHTBARRIER_3_INTERRUPT,
	MILLING_STATION,
	LIGHTBARRIER_3_CONNECT,
	LIGHTBARRIER_4_INTERRUPT,
	DRILLINGSTATION,
	LIGHTBARRIER_4_CONNECT,
	LIGHTBARRIER_5_INTERRUPT,
	LIGHTBARRIER_5_CONNECT,
	SPECTAL_ANALYSIS
}